load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "di",
    srcs = [
        "container.py",
        "deps.py",
    ],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/chat_service",
        "//take_home/causal_chains/agents/clients/di",
        "//take_home/causal_chains/agents/stores/causal_chain_store",
        "//take_home/causal_chains/agents/stores/messaging_store",
        "//take_home/causal_chains/agents/stores/turn_store",
        "//take_home/causal_chains/agents/agent_runner",
        "//take_home/causal_chains/agents/stub_runner",
        requirement("dependency-injector"),
        requirement("fastapi"),
    ],
)

pytest_test(
    name = "di_test",
    srcs = ["deps_test.py"],
    imports = ["../../../.."],
    deps = [
        ":di",
        "//take_home/causal_chains/agents/stores/causal_chain_store/protocol",
        requirement("dependency-injector"),
    ],
)
