load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "di",
    srcs = [
        "container.py",
        "deps.py",
    ],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/chat_service",
        "//take_home/causal_chains/agents/clients/di",
        "//take_home/causal_chains/agents/database/messaging_store",
        "//take_home/causal_chains/agents/database/turn_store:ddb_turn_store",
        "//take_home/causal_chains/agents/agent_runner",
        "//take_home/causal_chains/agents/stub_runner",
        requirement("dependency-injector"),
        requirement("fastapi"),
    ],
)

pytest_test(
    name = "deps_test",
    srcs = ["deps_test.py"],
    imports = ["../../../.."],
    deps = [":di"],
)
