load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "di",
    srcs = [
        "container.py",
        "deps.py",
        "ping_postgres.py",
    ],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/chat_service",
        "//take_home/causal_chains/agents/openai_runner",
        "//take_home/causal_chains/agents/stub_runner",
        requirement("dependency-injector"),
        requirement("fastapi"),
        requirement("psycopg"),
    ],
)

py_test(
    name = "deps_test",
    srcs = [
        "__test__.py",
        "deps_test.py",
    ],
    imports = ["../../../.."],
    main = "__test__.py",
    deps = [
        ":di",
        requirement("pytest"),
    ],
)

py_test(
    name = "ping_postgres_test",
    srcs = [
        "__test__.py",
        "ping_postgres_test.py",
    ],
    imports = ["../../../.."],
    main = "__test__.py",
    deps = [
        ":di",
        requirement("pytest"),
    ],
)
