load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "discover",
    srcs = ["discover.py"],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/agents/path_builder:discovered_situations",
        "//take_home/causal_chains/agents/models/causal_chains",
    ],
)

pytest_test(
    name = "discover_test",
    srcs = ["discover_test.py"],
    imports = ["../../../../.."],
    deps = [
        ":discover",
        "//take_home/causal_chains/agents/agents/path_builder:discovered_situations",
        "//take_home/causal_chains/agents/models/causal_chains",
    ],
)
