load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "subarray_sum_equals_k",
    srcs = ["subarray_sum_equals_k.py"],
    imports = ["."],
)

py_test(
    name = "subarray_sum_equals_k_test",
    srcs = [
        "__test__.py",
        "subarray_sum_equals_k_test.py",
    ],
    main = "__test__.py",
    deps = [
        ":subarray_sum_equals_k",
        requirement("pytest"),
    ],
)
