load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "subarray_sum_equals_k",
    srcs = ["subarray_sum_equals_k.py"],
    imports = ["."],
)

pytest_test(
    name = "subarray_sum_equals_k_test",
    srcs = ["subarray_sum_equals_k_test.py"],
    deps = [":subarray_sum_equals_k"],
)
