load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "turn_store",
    srcs = [
        "ddb_turn_store.py",
        "in_mem_turn_store.py",
    ],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/clients/dynamo_db/protocol",
        "//take_home/causal_chains/agents/stores/turn_store/protocol",
        "//take_home/causal_chains/agents/models/messaging/turn",
    ],
)

pytest_test(
    name = "turn_store_test",
    srcs = [
        "ddb_turn_store_test.py",
        "turn_store_test.py",
    ],
    imports = ["../../../../.."],
    deps = [
        ":turn_store",
        "//take_home/causal_chains/agents/models/messaging",
        "//take_home/causal_chains/agents/models/messaging/turn",
    ],
)
