load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "run_context",
    srcs = ["run_context.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        ":run_config",
        requirement("pydantic"),
    ],
)

py_library(
    name = "run_config",
    srcs = ["run_config.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

pytest_test(
    name = "run_context_test",
    srcs = ["run_context_test.py"],
    imports = ["../../../.."],
    deps = [":run_context"],
)
