load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "models",
    srcs = [
        "run_clients.py",
        "run_config.py",
        "run_context.py",
    ],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/stores/causal_chain_store/protocol",
        "//take_home/causal_chains/agents/stores/messaging_store/protocol",
        "//take_home/causal_chains/time/protocol",
        requirement("pydantic"),
    ],
)

pytest_test(
    name = "models_test",
    srcs = ["run_context_test.py"],
    imports = ["../../../.."],
    deps = [
        ":models",
    ],
)
