load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "protocol",
    srcs = ["protocol.py"],
    imports = ["../../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/models/causal_chains",
    ],
)

pytest_test(
    name = "protocol_test",
    srcs = ["protocol_test.py"],
    imports = ["../../../../../.."],
    deps = [
        ":protocol",
        "//take_home/causal_chains/agents/models/causal_chains",
    ],
)
