load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "range_sum_query_2d",
    srcs = ["range_sum_query_2d.py"],
    imports = ["."],
)

pytest_test(
    name = "range_sum_query_2d_test",
    srcs = ["range_sum_query_2d_test.py"],
    deps = [":range_sum_query_2d"],
)
