load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "pricer",
    srcs = ["pricer.py"],
    data = ["//take_home/causal_chains/agents/agents/pricer/prompts:pricer.md"],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/models/causal_chains",
        "//take_home/causal_chains/agents/models",
        requirement("openai"),
        requirement("openai-agents"),
    ],
)

pytest_test(
    name = "pricer_test",
    srcs = ["pricer_test.py"],
    data = ["//take_home/causal_chains/agents/agents/pricer/prompts:pricer.md"],
    imports = ["../../../../.."],
    deps = [
        ":pricer",
        "//take_home/causal_chains/agents/models/causal_chains",
        requirement("openai-agents"),
    ],
)
