load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "trapping_rain_water",
    srcs = ["trapping_rain_water.py"],
    imports = ["."],
)

py_test(
    name = "trapping_rain_water_test",
    srcs = [
        "__test__.py",
        "trapping_rain_water_test.py",
    ],
    main = "__test__.py",
    deps = [
        ":trapping_rain_water",
        requirement("pytest"),
    ],
)
