load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "trapping_rain_water",
    srcs = ["trapping_rain_water.py"],
    imports = ["."],
)

pytest_test(
    name = "trapping_rain_water_test",
    srcs = ["trapping_rain_water_test.py"],
    deps = [":trapping_rain_water"],
)
