load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "coin_change",
    srcs = ["coin_change.py"],
    imports = ["."],
)

pytest_test(
    name = "coin_change_test",
    srcs = ["coin_change_test.py"],
    deps = [":coin_change"],
)
