load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "di",
    srcs = ["container.py"],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/clients/dynamo_db:boto_dynamo_db",
        "//take_home/causal_chains/agents/clients/dynamo_db/protocol",
        "//take_home/causal_chains/agents/clients/graph_db:neo4j_client",
        "//take_home/causal_chains/agents/clients/graph_db/protocol",
        "//take_home/causal_chains/agents/clients/memcache",
        "//take_home/causal_chains/agents/clients/memcache:span_processor",
        requirement("boto3"),
        requirement("dependency-injector"),
        requirement("neo4j"),
    ],
)

pytest_test(
    name = "container_test",
    srcs = ["container_test.py"],
    imports = ["../../../../.."],
    deps = [
        ":di",
        "//take_home/causal_chains/agents/clients/dynamo_db/protocol",
        "//take_home/causal_chains/agents/clients/graph_db/protocol",
    ],
)
