load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "subset_sum",
    srcs = ["subset_sum.py"],
    imports = ["."],
)

pytest_test(
    name = "subset_sum_test",
    srcs = ["subset_sum_test.py"],
    deps = [":subset_sum"],
)
