load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "boto_dynamo_db",
    srcs = ["boto_dynamo_db.py"],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/clients/dynamo_db/protocol",
        requirement("boto3"),
    ],
)

pytest_test(
    name = "boto_dynamo_db_test",
    srcs = ["boto_dynamo_db_test.py"],
    imports = ["../../../../.."],
    deps = [":boto_dynamo_db"],
)
