load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "plan",
    srcs = ["plan.py"],
    imports = ["../../../../../"],
    visibility = ["//visibility:public"],
    deps = [requirement("pydantic")],
)

pytest_test(
    name = "plan_test",
    srcs = ["plan_test.py"],
    imports = ["../../../../../"],
    deps = [
        ":plan",
        requirement("pydantic"),
    ],
)
