load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "neo4j_client",
    srcs = ["neo4j_client.py"],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/clients/graph_db/protocol",
        "//take_home/causal_chains/agents/models/causal_chains",
        requirement("neo4j"),
    ],
)

pytest_test(
    name = "neo4j_client_test",
    srcs = ["neo4j_client_test.py"],
    imports = ["../../../../.."],
    deps = [
        ":neo4j_client",
        "//take_home/causal_chains/agents/clients/graph_db/protocol",
    ],
)
