load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "chat_service",
    srcs = ["chat_service.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/models:run_clients",
        "//take_home/causal_chains/agents/models:run_config",
        "//take_home/causal_chains/agents/models:run_context",
        "//take_home/causal_chains/agents/stores/causal_chain_store/protocol",
        "//take_home/causal_chains/agents/models/messaging",
        "//take_home/causal_chains/agents/agent_runner/protocol",
        "//take_home/causal_chains/agents/stores/messaging_store/protocol",
        "//take_home/causal_chains/agents/stores/turn_store/protocol",
        "//take_home/causal_chains/models",
    ],
)

pytest_test(
    name = "chat_service_test",
    srcs = ["chat_service_test.py"],
    imports = ["../../../.."],
    deps = [
        ":chat_service",
        "//take_home/causal_chains/agents/stores/messaging_store",
        "//take_home/causal_chains/agents/stores/turn_store",
        "//take_home/causal_chains/agents/models:run_clients",
        "//take_home/causal_chains/agents/models/messaging",
        "//take_home/causal_chains/agents/stub_runner",
        "//take_home/causal_chains/models",
    ],
)
