load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "models",
    srcs = [
        "conversation.py",
        "message.py",
        "turn.py",
        "turn_status.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

pytest_test(
    name = "models_test",
    srcs = [
        "conversation_test.py",
        "message_test.py",
        "turn_status_test.py",
        "turn_test.py",
    ],
    imports = ["../../.."],
    deps = [
        ":models",
        requirement("pydantic"),
    ],
)
