load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "models",
    srcs = [
        "conversation.py",
        "message.py",
        "sse_event.py",
        "turn.py",
        "turn_status.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

py_test(
    name = "turn_status_test",
    srcs = [
        "__test__.py",
        "turn_status_test.py",
    ],
    imports = ["../../.."],
    main = "__test__.py",
    deps = [
        ":models",
        requirement("pydantic"),
        requirement("pytest"),
    ],
)

py_test(
    name = "turn_test",
    srcs = [
        "__test__.py",
        "turn_test.py",
    ],
    imports = ["../../.."],
    main = "__test__.py",
    deps = [
        ":models",
        requirement("pytest"),
    ],
)

py_test(
    name = "conversation_test",
    srcs = [
        "__test__.py",
        "conversation_test.py",
    ],
    imports = ["../../.."],
    main = "__test__.py",
    deps = [
        ":models",
        requirement("pytest"),
    ],
)

py_test(
    name = "message_test",
    srcs = [
        "__test__.py",
        "message_test.py",
    ],
    imports = ["../../.."],
    main = "__test__.py",
    deps = [
        ":models",
        requirement("pytest"),
    ],
)

py_test(
    name = "sse_event_test",
    srcs = [
        "__test__.py",
        "sse_event_test.py",
    ],
    imports = ["../../.."],
    main = "__test__.py",
    deps = [
        ":models",
        requirement("pytest"),
    ],
)
