load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "stub_runner",
    srcs = ["stub_turn_runner.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/models",
        "//take_home/causal_chains/protocol",
    ],
)

py_test(
    name = "stub_turn_runner_test",
    srcs = [
        "__test__.py",
        "stub_turn_runner_test.py",
    ],
    imports = ["../../../.."],
    main = "__test__.py",
    deps = [
        ":stub_runner",
        "//take_home/causal_chains/models",
        requirement("pytest"),
    ],
)
