load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "health",
    srcs = ["health.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/di",
        "//take_home/causal_chains/agents/http_models:health_response",
        requirement("fastapi"),
    ],
)

py_test(
    name = "health_test",
    srcs = [
        "__test__.py",
        "health_test.py",
    ],
    imports = ["../../../.."],
    main = "__test__.py",
    deps = [
        ":health",
        "//take_home/causal_chains/agents/di",
        requirement("dependency-injector"),
        requirement("pytest"),
    ],
)
