load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "memcache",
    srcs = [
        "memcache.py",
        "span_processor.py",
    ],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/clients/memcache/protocol",
        requirement("openai-agents"),
    ],
)

pytest_test(
    name = "memcache_test",
    srcs = [
        "memcache_test.py",
        "span_processor_test.py",
    ],
    imports = ["../../../../.."],
    deps = [
        ":memcache",
        "//take_home/causal_chains/agents/clients/memcache/protocol",
    ],
)
