load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "main_app",
    srcs = ["main_app.py"],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/di",
        "//take_home/causal_chains/agents/endpoints:conversation",
        "//take_home/causal_chains/agents/endpoints:health",
        requirement("fastapi"),
    ],
)

py_library(
    name = "main",
    srcs = ["main.py"],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        ":main_app",
        "//take_home/causal_chains/agents/di",
        requirement("click"),
        requirement("uvicorn"),
    ],
)

py_test(
    name = "main_app_test",
    srcs = [
        "__test__.py",
        "main_app_test.py",
    ],
    imports = ["../../.."],
    main = "__test__.py",
    deps = [
        ":main_app",
        "//take_home/causal_chains/agents/di",
        requirement("dependency-injector"),
        requirement("fastapi"),
        requirement("httpx"),
        requirement("pytest"),
    ],
)
