load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "agents",
    srcs = [
        "main.py",
        "main_app.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/di",
        "//take_home/causal_chains/agents/endpoints",
        "//take_home/causal_chains/agents/observability/endpoint_logging",
        requirement("braintrust"),
        requirement("click"),
        requirement("fastapi"),
        requirement("openai-agents"),
        requirement("uvicorn"),
    ],
)

pytest_test(
    name = "agents_test",
    srcs = ["main_app_test.py"],
    imports = ["../../.."],
    deps = [
        ":agents",
        "//take_home/causal_chains/agents/di",
        "//take_home/causal_chains/agents/models/causal_chains",
        "//take_home/causal_chains/agents/models/messaging",
        requirement("dependency-injector"),
        requirement("fastapi"),
        requirement("httpx"),
    ],
)
