load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")
load("//tools/pytest:defs.bzl", "pytest_test")

py_binary(
    name = "offline",
    srcs = ["offline.py"],
    imports = ["../../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/chat_service",
        "//take_home/causal_chains/agents/clients/memcache",
        "//take_home/causal_chains/agents/clients/memcache/protocol",
        "//take_home/causal_chains/agents/eval/offline/di",
        "//take_home/causal_chains/agents/models",
        "//take_home/causal_chains/agents/models/messaging",
        requirement("braintrust"),
        requirement("click"),
        requirement("openai"),
        requirement("openai-agents"),
    ],
)

pytest_test(
    name = "offline_test",
    srcs = ["offline_test.py"],
    imports = ["../../../../.."],
    deps = [
        ":offline",
        "//take_home/causal_chains/agents/agent_runner",
        "//take_home/causal_chains/agents/clients/memcache",
    ],
)
