load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "messaging",
    srcs = ["sse_event.py"],
    imports = ["../../../../../"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

pytest_test(
    name = "sse_event_test",
    srcs = ["sse_event_test.py"],
    imports = ["../../../../../"],
    deps = [":messaging"],
)
