from enum import StrEnum


class ConversationStatus(StrEnum):
    OPEN = "OPEN"
    RESTRICTED = "RESTRICTED"
    IN_PROGRESS_WITHOUT_MESSAGES = "IN_PROGRESS_WITHOUT_MESSAGES"
    IN_PROGRESS_WITH_MESSAGES = "IN_PROGRESS_WITH_MESSAGES"
    CLOSED = "CLOSED"
