load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "models",
    srcs = [
        "conversation_messages_response.py",
        "conversation_response.py",
        "post_message_response.py",
        "text_input_state.py",
        "thinking_state.py",
        "turn_descriptor.py",
        "user_interaction_state.py",
    ],
    imports = ["../../../../../"],
    visibility = ["//visibility:public"],
    deps = [
        "//take_home/causal_chains/agents/models/messaging",
        "//take_home/causal_chains/agents/models/turn",
        requirement("pydantic"),
    ],
)

pytest_test(
    name = "models_test",
    srcs = [
        "conversation_messages_response_test.py",
        "conversation_response_test.py",
        "post_message_response_test.py",
        "text_input_state_test.py",
        "thinking_state_test.py",
        "turn_descriptor_test.py",
        "user_interaction_state_test.py",
    ],
    imports = ["../../../../../"],
    deps = [
        ":models",
        "//take_home/causal_chains/agents/models/messaging",
        "//take_home/causal_chains/agents/models/turn",
        requirement("pydantic"),
    ],
)
