load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "http_models",
    srcs = [
        "health_response.py",
        "post_message_body.py",
    ],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

pytest_test(
    name = "http_models_test",
    srcs = [
        "health_response_test.py",
        "post_message_body_test.py",
    ],
    imports = ["../../../.."],
    deps = [":http_models"],
)
