load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "health_response",
    srcs = ["health_response.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

py_library(
    name = "post_message_body",
    srcs = ["post_message_body.py"],
    imports = ["../../../.."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pydantic"),
    ],
)

py_test(
    name = "post_message_body_test",
    srcs = [
        "__test__.py",
        "post_message_body_test.py",
    ],
    imports = ["../../../.."],
    main = "__test__.py",
    deps = [
        ":post_message_body",
        requirement("pytest"),
    ],
)

py_test(
    name = "health_response_test",
    srcs = [
        "__test__.py",
        "health_response_test.py",
    ],
    imports = ["../../../.."],
    main = "__test__.py",
    deps = [
        ":health_response",
        requirement("pytest"),
    ],
)
