load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/pytest:defs.bzl", "pytest_test")

py_library(
    name = "turn",
    srcs = [
        "turn.py",
        "turn_status.py",
    ],
    imports = ["../../../../../../"],
    visibility = ["//visibility:public"],
    deps = [requirement("pydantic")],
)

pytest_test(
    name = "turn_test",
    srcs = [
        "turn_status_test.py",
        "turn_test.py",
    ],
    imports = ["../../../../../../"],
    deps = [
        ":turn",
        requirement("pydantic"),
    ],
)
